### ISSUE TITLE
Setup GH actions

### ISSUE THREAD

**Issue by Jeconias** [lab259/go-my-ast-hurts#2]
If someone could implement Github actions here would be awesome!

**Comment by edjroz** [comment]
I'd like to help with this.

**Comment by Jeconias** [comment]
> I'd like to help with this. Would you mind assigning it ?
> 
> What type of steps would you like on the Actions? running tests and ?

Ok, you may follow this example: https://github.com/lab259/errors/blob/master/.github/workflows/go.yml
